[build]
  base = "/"
  command = "pip install -r requirements.txt && python app.py build"
  publish = "static"

[build.environment]
  PYTHON_VERSION = "3.9"
  FLASK_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "flask"
  targetPort = 5000 